### ISSUE TITLE
Monorepo initial props not working

### ISSUE THREAD

**Issue by MartinYounghoonKim** [kyle-mccarthy/nest-next#41]
**Describe the bug**
After cloning the repository, I've start the monorepo's dev server. Server works fine, but initial props not working. This is just example code in [here](https://github.com/kyle-mccarthy/nest-next/tree/master/examples/monorepo).

```typescript
// server/src/app.controller.ts
@Controller()
export class AppController {
  @Render('index')
  @Get()
  public index(): IndexProps {
    return { message: 'from server' }; // If controller's method return message,
  }
}

// ui/pages/index.ts
IndexPage.getInitialProps = async context => {
  if (context.req) {
    return (context.query as unknown) as IndexProps; // when the first server side rendering occurs, I think I can receive  'from server' message, but not working
  }
  return { message: 'from client' };
};

```

**Expected behavior**
Receive the initial props in ui component's getInitialProps.

**To Reproduce**

Repository URL: 

**Version**
- next.js: 9.3.5
- nest: 6.11.11
- nest-next: 9.2.0

**Additional context**

**Comment by kyle-mccarthy** [comment]
In your IndexPage.getInitialProps if you `console.log(context.query)` what is the output?

**Comment by MartinYounghoonKim** [comment]
@kyle-mccarthy 
when I tried to logging like this,

```typescript
IndexPage.getInitialProps = async context => {
  console.log(context.query) // 👈logging here
  if (context.req) {
    return (context.query as unknown) as IndexProps;
  }
  return { message: 'from client' };
};

// {}
// I got empty object. 
```

**Comment by kyle-mccarthy** [comment]
Fixed by #43

**Comment by MartinYounghoonKim** [comment]
@kyle-mccarthy 
Sorry to bother you. It didn't solve the problem.

**Comment by kyle-mccarthy** [comment]
@MartinYounghoonKim it's no problem and sorry about that you are correct, the props aren't getting forwarded from the server. @boenrobot do you have any ideas about this one?

**Comment by kyle-mccarthy** [comment]
@MartinYounghoonKim Can you confirm that you built the ui with `yarn build` from the `ui` directory before running the server from the `server` dir?

**Comment by MartinYounghoonKim** [comment]
@kyle-mccarthy okay, I'll check

**Comment by MartinYounghoonKim** [comment]
@kyle-mccarthy I think it solved. what was the problem ?

**Comment by kyle-mccarthy** [comment]
@MartinYounghoonKim I don't know the exact reason, but the ui folder must have an existing build for the server to correctly send the props. I'm going to close this issue since it seems to resolve the problem.
